<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.hesung.openapi</groupId>
    <artifactId>openapi-developer-service</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>openapi-developer-service</name>
    <description>OpenAPI Platform Aggregation Service</description>

    <parent>
        <groupId>com.hesung.hsmf</groupId>
        <artifactId>hsmf-parent</artifactId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>

    <properties>
        <lombok.version>1.18.24</lombok.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.hesung.hsmf</groupId>
            <artifactId>hsmf-framework-base</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hesung.hsmf</groupId>
            <artifactId>hsmf-framework-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hesung.hsmf</groupId>
            <artifactId>hsmf-framework-feignclient</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hesung.openapi</groupId>
            <artifactId>openapi-console-starter</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}-${activatedProfile}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
